services:
  web:
    build: .
    ports:
      - "8888:8888"  # Sesuaikan dengan settings.API_PORT kamu

    environment:
      - DEBUG=True
    env_file:
      - .env
    volumes:
      - ./credentials.json:/app/credentials.json
    restart: always
